/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "prog.h"

bool_t
xdr_buffer (XDR *xdrs, buffer *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->data, ~0))
		 return FALSE;
	return TRUE;
}
