/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROG_H_RPCGEN
#define _PROG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	char command[1024];
};
typedef struct input input;

struct result {
	char output[1024];
};
typedef struct result result;

#define RLSPROG 0x20000008
#define RLSVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RLS 1
extern  result * rls_1(input *, CLIENT *);
extern  result * rls_1_svc(input *, struct svc_req *);
extern int rlsprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RLS 1
extern  result * rls_1();
extern  result * rls_1_svc();
extern int rlsprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);
extern  bool_t xdr_result (XDR *, result*);

#else /* K&R C */
extern bool_t xdr_input ();
extern bool_t xdr_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROG_H_RPCGEN */
